plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "D:\\University\\2025-2026\\semester 2\\网站\\个人网站"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]